on push
jobs:
  build-node: 
    runs-on: debain
    container: node:16
    steps:
    - run: node --version
    - run: npm --version
    - uses: actions/checkout@v3
    - run: npm insrall
    - run: node server.js